### ISSUE TITLE
Translate subcategories names and other main texts

### ISSUE THREAD

**Issue by smellai** [arduino/reference-fr#1]
- Arduino Reference
- The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords.
- functions
- For controlling the Arduino board and performing computations.
- Digital I/O
- Analog I/O
- Zero, Due & MKR Family
- Advanced I/O
- Time
- Math
- Trigonometry
- Characters
- Random Numbers
- Bits and Bytes
- External Interrupts
- Interrupts
- Communication
- Serial
- Stream
- USB
- Keyboard
- Mouse
- variables
- Arduino data types and constants.
- Constants
- Conversion
- Data Types
- Variable Scope & Qualifiers
- Utilities
- structure
- The elements of Arduino (C++) code.
- Sketch
- Control Structure
- Further Syntax
- Arithmetic Operators
- Comparison Operators
- Boolean Operators
- Pointer Access Operators
- Bitwise Operators
- Compound Operators

**Comment by ThomArmax** [comment]
I have [forked the repository](https://github.com/ThomArmax/reference-fr) and I am currently translating all the "Constants" section

**Comment by ThomArmax** [comment]
I am about to create a pull request about this issue. I have translated almost all subcategories, categories and titles.
But I can't find any file referencing those texts :

- The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords.
- The elements of Arduino (C++) code.
- For controlling the Arduino board and performing computations
- Arduino data types and constants.

Do you have an idea where I can found these texts ?

**Comment by smellai** [comment]
Hi @ThomArmax you can write the translations here and I will update them, thanks

**Comment by ThomArmax** [comment]
Hi @smellai 
- The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords. **(not so sure about the translation)** 
> La référence du langage de programmation Arduino, organisée en Fonctions, Variables, Constantes et Structures.
- The elements of Arduino (C++) code.
> Les éléments du code Arduino (C++)
- For controlling the Arduino board and performing computations
> Pour contrôler la carte Arduino et effectuer des calculs
- Arduino data types and constants
> Types de données et constantes de l'Arduino

**Comment by smellai** [comment]
Thanks @ThomArmax !
can you provide the whole list above translated?

**Comment by ThomArmax** [comment]
I check. Some weeks ago, I translated all titles and subcategories in a branch. I can create a pull request if you want.

See https://github.com/ThomArmax/reference-fr/tree/subcategories-translation

**Comment by smellai** [comment]
I need to translate the translations file in the private repo containing the rendering engine

**Comment by ThomArmax** [comment]
- Arduino Reference = Référence Arduino
- Digital I/O = E/S Numériques
- Analog I/O = E/S Analogiques
- Zero, Due & MKR Family = Famille Zero, Due & MKR
- Advanced I/O = E/S Avancées
- Time = Temps
- Math = Mathématiques
- Trigonometry = Trigonométrie
- Characters = Caractères
- Random Numbers = Nombres Aléatoires
- Bits and Bytes = Bits et Octets
- External Interrupts = Interruptions Externes
- Interrupts = Interruptions
- Communication = Communication
- Serial = Série
- Stream = Flux
- USB = USB
- Keyboard = Clavier
- Mouse = Souris
- variables = Variables
- Arduino data types and constants = Types de données et constantes de l'Arduino
- Constants = Constantes
- Conversion = Conversion
- Data Types = Types de Données
- Variable Scope & Qualifiers = Portée & Qualifieurs des Variables
- Utilities = Utilitaires
- structure = Structure
- The elements of Arduino (C++) code. = Les éléments du code Arduino (C++)
- Sketch = Sketch
- Control Structure = Structures de Contrôle
- Further Syntax = Autre Syntaxe
- Arithmetic Operators = Opérateurs Arithmétiques
- Comparison Operators = Opérateurs de Comparaison
- Boolean Operators = Opérateurs Booléens
- Pointer Access Operators = Opérateurs d'accès aux Pointeurs
- Bitwise Operators = Opérateurs Bit à Bit
- Compound Operators = Opérateurs Composés

**Comment by smellai** [comment]
Thank you! Here the translations: https://www.arduino.cc/reference/fr/

**Comment by ThomArmax** [comment]
You're welcome. It's a pleasure to contribute to the Arduino community
