### ISSUE TITLE
Translate Site texts

### ISSUE THREAD

**Issue by smellai** [arduino/reference-fr#3]
- id: pageTitle
  translation: Language Reference

- id: pageDescription
  translation: "Arduino programming language can be divided in three main parts: structure, values (variables and constants), and functions."

- id: language
  translation: Language

- id: functions
  translation: functions

- id: variables
  translation: variables

- id: structure
  translation: structure

- id: libraries
  translation: Libraries

- id: glossary
  translation: Glossary

- id: editButton
  translation: Edit This Page

- id: license
  translation: "The Arduino Reference text is licensed under a <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">Creative Commons Attribution-Share Alike 3.0 License</a>."

- id: githubLink
  translation: "Find anything that can be improved? <a href=\"https://github.com/arduino/reference-en\" target=\"_blank\" rel=\"noopener\">Suggest corrections and new documentation via GitHub.</a>"

- id: tutorialLink
  translation: "Doubts on how to use Github? Learn everything you need to know in <a href=\"https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target=\"_blank\" rel=\"noopener\">this tutorial</a>."

**Comment by ThomArmax** [comment]
- id: pageTitle
translation: Référence du langage
- id: pageDescription
translation: Le langage de programmation Arduino peut être divisé en trois parties principales: structures, valeurs (variables et constantes), et fonctions
- id: language
translation: Langage
- id: functions
translation: fonctions
-id: variables
translation: variables
- id: structure
translation: structure
- id: libraries
translation: Librairies
- id: glossary
translation: glossaire
-id: editButton
translation: Éditer Cette Page
- id: license
translation: "Le texte de la référence Arduino est sous licence \<a href="https://creativecommons.org/licenses/by-sa/3.0/\" target="_blank" rel="noopener">Creative Commons Attribution-Share Alike 3.0"

- id: githubLink
translation: "Vous avez trouver quelque chose qui peut être amélioré? \<a href="https://github.com/arduino/reference-fr\" target="_blank" rel="noopener">Suggérez des corrections et de la nouvelle documentation via GitHub."
- id: tutorialLink
translation: "Des doutes sur la façon d'utiliser Github? Apprenez tout ce que vous devez savoir dans \<a href="https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target="_blank" rel="noopener">ce tutoriel."

**Comment by smellai** [comment]
Updated (https://www.arduino.cc/reference/fr/)! Thank you
